-- Delete only the 50 specific Science - Year 3 UK beginner questions (currently in Medium)
DELETE FROM questions 
WHERE category = 'Science - Year 3 UK' 
AND question_text IN (
  'Which part of a plant is responsible for absorbing water and minerals from the soil?',
  'What do plants need from the sun to help them make their own food?',
  'Which part of the plant holds it upright and carries water to the leaves?',
  'What is the main job of a flower on a plant?',
  'Which of these is NOT something a plant needs to grow well?',
  'What is it called when pollen is moved from one flower to another?',
  'How might a dandelion seed travel away from its parent plant?',
  'What do we call the stage when a seed starts to grow into a tiny plant?',
  'Which nutrient is mainly found in meat, fish, and beans to help our bodies grow and repair?',
  'Why do humans and some animals have skeletons?',
  'An animal without a backbone is called a what?',
  'How do muscles work to move our bones?',
  'Which of these is a type of sedimentary rock?',
  'What are fossils made of?',
  'What is the organic part of soil made from dead plants and animals called?',
  'Which rock is very hard and often used for kitchen worktops?',
  'How is soil created?',
  'Darkness is defined as the absence of what?',
  'What happens when light hits a mirror?',
  'Why should we never look directly at the sun?',
  'How is a shadow formed?',
  'Which word describes a material that lets NO light through?',
  'If you move an object closer to a light source, what happens to the shadow?',
  'Which of these is a push force?',
  'What force acts between two surfaces sliding against each other?',
  'Which surface would likely have the MOST friction for a toy car?',
  'What are the two ends of a magnet called?',
  'What happens when you put two North poles of magnets together?',
  'Which of these metals is magnetic?',
  'What does a magnet do to a paperclip made of steel?',
  'Which part of the plant makes the most food?',
  'What type of food provides us with quick energy?',
  'Which of these is an example of an invertebrate?',
  'Which bone protects your brain?',
  'What do we call rocks that are formed from cooling lava or magma?',
  'Which of these is a natural source of light?',
  'Which material is transparent?',
  'A magnet will attract which of these objects?',
  'In which direction does a compass needle usually point?',
  'Which of these helps to keep our bones strong?',
  'What are the three main types of rocks?',
  'Which of these is NOT a way seeds are dispersed?',
  'What happens to your pupil (the black part of your eye) in a dark room?',
  'Which force is used when you ring a doorbell?',
  'What is the name of the \'skeleton\' on the outside of an insect\'s body?',
  'Which part of the plant attracts bees with its bright colors?',
  'Which of these materials is most likely to be translucent?',
  'What kind of rock is formed when existing rocks are changed by heat or pressure?',
  'If two magnets pull towards each other, they are doing what?',
  'Why do plants need space between them to grow?'
);
